### ISSUE TITLE
Thrift Interface

### ISSUE THREAD

**Issue by harshal-zetaris** [naushadh/hive-metastore#1]
Does this come with frontending of a thrift interface as shown here?

![image](https://github.com/naushadh/hive-metastore/assets/112365410/715c53c9-3f6f-4e03-8fc2-817673bb75fd)

**Comment by naushadh** [comment]
Yes, this project _is_ that green hexagon shown in your diagram. You can [configure](https://github.com/naushadh/hive-metastore#configuration) the MetaStoreDB as you like.

**Comment by naushadh** [comment]
I tried a fresh new clone and it works for me

```bash
$ docker compose up -d
[+] Running 4/4
 ✔ Container hive-metastore-localstack-1  Healthy                                                                   10.8s 
 ✔ Container hive-metastore-postgres-1    Healthy                                                                   30.8s 
 ✔ Container hive-metastore-s3_setup-1    Started                                                                   11.0s 
 ✔ Container hive-metastore-app-1         Started                                                                   31.0s 
$ docker compose ps
NAME                          IMAGE                       COMMAND                  SERVICE             CREATED              STATUS                    PORTS
hive-metastore-app-1          hive-metastore-app          "./run.sh"               app                 About a minute ago   Up 8 seconds              0.0.0.0:9083->9083/tcp
hive-metastore-localstack-1   localstack/localstack:1.1   "docker-entrypoint.sh"   localstack          About a minute ago   Up 39 seconds (healthy)   4510-4559/tcp, 5678/tcp, 0.0.0.0:4566->4566/tcp
hive-metastore-postgres-1     postgres:14-alpine          "docker-entrypoint.s…"   postgres            About a minute ago   Up 39 seconds (healthy)   0.0.0.0:5432->5432/tcp
```

Can you share the output of these commands shown above?

**Comment by naushadh** [comment]
@harshal-zetaris Is this still an issue? I'd prefer to keep issues clean and close out stale items.

**Comment by harshal-zetaris** [comment]
> @harshal-zetaris Is this still an issue? I'd prefer to keep issues clean and close out stale items.

Naushad, I never got it to work really and hence moved on to alternative solutions. you can close the issue.

**Comment by naushadh** [comment]
Oh I see; I started this project because too many folks were writing custom dockerfile and shell scripts to bootstrap the thrift/metastore and hoped this would eliminate such boilerplate. If/when you're interested in giving this a shot again, please share the output of commands shown here https://github.com/naushadh/hive-metastore/issues/1#issuecomment-1565196441 and we can track down what's blocking you.
